// Generated by gencpp from file demo/AddTwoInts.msg
// DO NOT EDIT!


#ifndef DEMO_MESSAGE_ADDTWOINTS_H
#define DEMO_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <demo/AddTwoIntsRequest.h>
#include <demo/AddTwoIntsResponse.h>


namespace demo
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace demo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::demo::AddTwoInts > {
  static const char* value()
  {
    return "2213f49e9419ab680f60ff0e7014facd";
  }

  static const char* value(const ::demo::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::demo::AddTwoInts > {
  static const char* value()
  {
    return "demo/AddTwoInts";
  }

  static const char* value(const ::demo::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::demo::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::demo::AddTwoInts > 
template<>
struct MD5Sum< ::demo::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::demo::AddTwoInts >::value();
  }
  static const char* value(const ::demo::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::demo::AddTwoIntsRequest> should match 
// service_traits::DataType< ::demo::AddTwoInts > 
template<>
struct DataType< ::demo::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::demo::AddTwoInts >::value();
  }
  static const char* value(const ::demo::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::demo::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::demo::AddTwoInts > 
template<>
struct MD5Sum< ::demo::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::demo::AddTwoInts >::value();
  }
  static const char* value(const ::demo::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::demo::AddTwoIntsResponse> should match 
// service_traits::DataType< ::demo::AddTwoInts > 
template<>
struct DataType< ::demo::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::demo::AddTwoInts >::value();
  }
  static const char* value(const ::demo::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEMO_MESSAGE_ADDTWOINTS_H
