// Generated by gencpp from file demo/find_MeResponse.msg
// DO NOT EDIT!


#ifndef DEMO_MESSAGE_FIND_MERESPONSE_H
#define DEMO_MESSAGE_FIND_MERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace demo
{
template <class ContainerAllocator>
struct find_MeResponse_
{
  typedef find_MeResponse_<ContainerAllocator> Type;

  find_MeResponse_()
    : found(false)  {
    }
  find_MeResponse_(const ContainerAllocator& _alloc)
    : found(false)  {
    }



   typedef uint8_t _found_type;
  _found_type found;




  typedef boost::shared_ptr< ::demo::find_MeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::demo::find_MeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct find_MeResponse_

typedef ::demo::find_MeResponse_<std::allocator<void> > find_MeResponse;

typedef boost::shared_ptr< ::demo::find_MeResponse > find_MeResponsePtr;
typedef boost::shared_ptr< ::demo::find_MeResponse const> find_MeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::demo::find_MeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::demo::find_MeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace demo

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'demo': ['/home/vcoder/ros_ws/src/demo/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::demo::find_MeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::demo::find_MeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::demo::find_MeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::demo::find_MeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::demo::find_MeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::demo::find_MeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::demo::find_MeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d6c4ae35878abbcf43ece19ba68d70a6";
  }

  static const char* value(const ::demo::find_MeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd6c4ae35878abbcfULL;
  static const uint64_t static_value2 = 0x43ece19ba68d70a6ULL;
};

template<class ContainerAllocator>
struct DataType< ::demo::find_MeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "demo/find_MeResponse";
  }

  static const char* value(const ::demo::find_MeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::demo::find_MeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool found\n\
\n\
";
  }

  static const char* value(const ::demo::find_MeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::demo::find_MeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.found);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct find_MeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::demo::find_MeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::demo::find_MeResponse_<ContainerAllocator>& v)
  {
    s << indent << "found: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.found);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEMO_MESSAGE_FIND_MERESPONSE_H
