// Generated by gencpp from file demo/find_Me.msg
// DO NOT EDIT!


#ifndef DEMO_MESSAGE_FIND_ME_H
#define DEMO_MESSAGE_FIND_ME_H

#include <ros/service_traits.h>


#include <demo/find_MeRequest.h>
#include <demo/find_MeResponse.h>


namespace demo
{

struct find_Me
{

typedef find_MeRequest Request;
typedef find_MeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct find_Me
} // namespace demo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::demo::find_Me > {
  static const char* value()
  {
    return "2fa1f59afa4c021be31b726df9e5e8ef";
  }

  static const char* value(const ::demo::find_Me&) { return value(); }
};

template<>
struct DataType< ::demo::find_Me > {
  static const char* value()
  {
    return "demo/find_Me";
  }

  static const char* value(const ::demo::find_Me&) { return value(); }
};


// service_traits::MD5Sum< ::demo::find_MeRequest> should match 
// service_traits::MD5Sum< ::demo::find_Me > 
template<>
struct MD5Sum< ::demo::find_MeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::demo::find_Me >::value();
  }
  static const char* value(const ::demo::find_MeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::demo::find_MeRequest> should match 
// service_traits::DataType< ::demo::find_Me > 
template<>
struct DataType< ::demo::find_MeRequest>
{
  static const char* value()
  {
    return DataType< ::demo::find_Me >::value();
  }
  static const char* value(const ::demo::find_MeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::demo::find_MeResponse> should match 
// service_traits::MD5Sum< ::demo::find_Me > 
template<>
struct MD5Sum< ::demo::find_MeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::demo::find_Me >::value();
  }
  static const char* value(const ::demo::find_MeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::demo::find_MeResponse> should match 
// service_traits::DataType< ::demo::find_Me > 
template<>
struct DataType< ::demo::find_MeResponse>
{
  static const char* value()
  {
    return DataType< ::demo::find_Me >::value();
  }
  static const char* value(const ::demo::find_MeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEMO_MESSAGE_FIND_ME_H
