// Generated by gencpp from file camera_sub/MPerson.msg
// DO NOT EDIT!


#ifndef CAMERA_SUB_MESSAGE_MPERSON_H
#define CAMERA_SUB_MESSAGE_MPERSON_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace camera_sub
{
template <class ContainerAllocator>
struct MPerson_
{
  typedef MPerson_<ContainerAllocator> Type;

  MPerson_()
    : name()
    , age(0)  {
    }
  MPerson_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , age(0)  {
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef int32_t _age_type;
  _age_type age;




  typedef boost::shared_ptr< ::camera_sub::MPerson_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::camera_sub::MPerson_<ContainerAllocator> const> ConstPtr;

}; // struct MPerson_

typedef ::camera_sub::MPerson_<std::allocator<void> > MPerson;

typedef boost::shared_ptr< ::camera_sub::MPerson > MPersonPtr;
typedef boost::shared_ptr< ::camera_sub::MPerson const> MPersonConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::camera_sub::MPerson_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::camera_sub::MPerson_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace camera_sub

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'camera_sub': ['/home/vcoder/ros_ws/src/camera_sub/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::camera_sub::MPerson_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::camera_sub::MPerson_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera_sub::MPerson_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera_sub::MPerson_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera_sub::MPerson_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera_sub::MPerson_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::camera_sub::MPerson_<ContainerAllocator> >
{
  static const char* value()
  {
    return "83da5ca00b8e049b0559653a472c88a5";
  }

  static const char* value(const ::camera_sub::MPerson_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x83da5ca00b8e049bULL;
  static const uint64_t static_value2 = 0x0559653a472c88a5ULL;
};

template<class ContainerAllocator>
struct DataType< ::camera_sub::MPerson_<ContainerAllocator> >
{
  static const char* value()
  {
    return "camera_sub/MPerson";
  }

  static const char* value(const ::camera_sub::MPerson_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::camera_sub::MPerson_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n\
int32 age\n\
";
  }

  static const char* value(const ::camera_sub::MPerson_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::camera_sub::MPerson_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.age);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct MPerson_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::camera_sub::MPerson_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::camera_sub::MPerson_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "age: ";
    Printer<int32_t>::stream(s, indent + "  ", v.age);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAMERA_SUB_MESSAGE_MPERSON_H
